try{
    console.log(a + b);
}catch(Err_Obj){
    console.log("An Error Occurred");

    //To Output Error:
    //console.log(Err_Obj);
}

console.log("My Program is still running");